name: PocketVote
main: ProjectInfinity\PocketVote\PocketVote
version: 2.1.3
api: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6]
author: ProjectInfinity
permissions:
  pocketvote.admin:
    description: "Allows player to manage PocketVote"
    default: op
  pocketvote.vote:
    description: "Allows a player to use the /vote command"
    default: true