name: PocketVote
main: ProjectInfinity\PocketVote\PocketVote
version: 1.3.1
api: [3.0.0-ALPHA3]
author: ProjectInfinity
permissions:
  pocketvote.admin:
    description: "Allows player to manage PocketVote"
    default: op