version: 0
identity: ''
secret: ''
lock: false
vote-expiration: 7
opt-out-usage: false
onvote:
  - cmd: tell %player Thanks for voting at %site!
    player-online: true
  - cmd: say Thanks for voting for us at %site, %player!
    player-online: false
votes: []